name: Release

on:
  workflow_dispatch:
    inputs:
      modName:
        description: Mod name
        required: true
        default: UseSaveDirectory
      versionBumpType:
        description: Can be MAJOR, MINOR or PATCH
        required: true
        default: MAJOR
      changelogDescription:
        description: Markdown to add to changelog
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - name: Setup Git
        run: |
          set -eux
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build
        run: dotnet build -c Release

      - name: Release
        uses: actions/github-script@v7
        env:
          modName: ${{ github.event.inputs.modName }}
          versionBumpType: ${{ github.event.inputs.versionBumpType }}
          changelogDescription: ${{ github.event.inputs.changelogDescription }}
        with:
          script: |
            Object.assign(global, { github, context, core });
            return import('${{ github.workspace }}/.github/workflows/release.mjs');
